FI.PORTAL/Controllers/CustomerRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.PORTAL.dbconnect;
using FI.PORTAL.Models;
using FI.PORTAL.Report;
using FI.PORTAL.ViewModels;

namespace FI.PORTAL.Controllers
{
    public class CustomerRegistrationController : Controller
    {
        // GET: CustomerRequests
        CRP_SYSEntities CRP_dbObj = new CRP_SYSEntities();

        int CO_ROLE = 1;
        int CM_ROLE = 6;
        int FM_ROLE = 7;
        int GM_ROLE = 8;
        int ADMIN_ROLE = 100;
        int role;


        public ActionResult Index(string findby)
        {         
            if (findby == null)
            {
                // ---------- Updated from All -> Pending in order to view pending requests first --------- CMUpdate 
                ViewBag.findString = "Pending";
                //ViewBag.findString = "All";
            }
            else if (findby.Equals("Approved"))
            {
                ViewBag.findString = "Approved";
            }
            else if (findby.Equals("Pending"))
            {
                ViewBag.findString = "Pending";
            }
            else if (findby.Equals("All"))
            {
                ViewBag.findString = "All";
            }
            else if (findby.Equals("Declined")) //----------------- View the declined requests only ------------------ CMUpdate
            {
                ViewBag.findString = "Declined"; 
            }
            else
            {
                ViewBag.findString = "Invalid";
            }

            try
            {
                role = Convert.ToInt16(Session["role"].ToString());
            }
            catch (Exception e)
            {
                Response.Redirect("/Login/UserLogin", false);
            }

            if (role == CO_ROLE)
            {
                if (findby != null)
                {
                    if (findby.Equals("All"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 5).ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Pending"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 5 && r.CurrentStat != "approvedByGM" && r.CurrentStat != "approvedByFM" && r.CurrentStat != "approvedByCM").ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Approved"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => (r.Level >= 5 && r.CurrentStat == "approvedByGM") || (r.Level >= 5 && r.CurrentStat == "approvedByFM") || (r.Level >= 5 && r.CurrentStat == "approvedByCM")).ToList();
                        return View(res);
                    }
                    else
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 5).ToList();
                        return View(res);
                    }
                }
                else
                {
                    var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 5).ToList();
                    return View(res);
                }

            }
            else if (role == CM_ROLE)
            {
                if (findby != null)
                {
                    if (findby.Equals("All"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 6).ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Pending")) // ------------------ updated the query to ignore pendingCO and declineCO for thye pending requests
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 6 && r.CurrentStat != "approvedByGM" && r.CurrentStat != "approvedByFM" && r.CurrentStat != "approvedByCM" && r.CurrentStat != "pendingCO" && r.CurrentStat != "declineCO").ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Approved"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => (r.Level >= 6 && r.CurrentStat == "approvedByGM") || (r.Level >= 5 && r.CurrentStat == "approvedByFM") || (r.Level >= 5 && r.CurrentStat == "approvedByCM")).ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Declined"))   // --------------  If declineCM selected  ------------ CMUpdate
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 6 && r.CurrentStat == "declineCM").ToList();
                        return View(res);
                    }
                    else
                    {                       
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 6).ToList();                        
                        return View(res);
                    }
                }
                else
                {
                    // Changed from All to pending in order to view only pending items -------------------- CMUpdate
                    var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 6 && r.CurrentStat != "approvedByGM" && r.CurrentStat != "approvedByFM" && r.CurrentStat != "approvedByCM" && r.CurrentStat != "pendingCO" && r.CurrentStat != "declineCO").ToList();
                    //var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 6).ToList();
                    return View(res);
                }

            }
            else if (role == FM_ROLE)
            {
                if (findby != null)
                {
                    if (findby.Equals("All"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 7).ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Pending"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 7 && r.CurrentStat != "approvedByGM" && r.CurrentStat != "approvedByFM" && r.CurrentStat != "approvedByCM").ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Approved"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => (r.Level >= 7 && r.CurrentStat == "approvedByGM") || (r.Level >= 5 && r.CurrentStat == "approvedByFM") || (r.Level >= 5 && r.CurrentStat == "approvedByCM")).ToList();
                        return View(res);
                    }
                    else
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 7).ToList();
                        return View(res);
                    }
                }
                else
                {
                    var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 7).ToList();
                    return View(res);
                }

            }
            else if (role == GM_ROLE)
            {
                if (findby != null)
                {
                    if (findby.Equals("All"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 8).ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Pending"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 8 && r.CurrentStat != "approvedByGM" && r.CurrentStat != "approvedByFM" && r.CurrentStat != "approvedByCM").ToList();
                        return View(res);
                    }
                    else if (findby.Equals("Approved"))
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => (r.Level >= 8 && r.CurrentStat == "approvedByGM") || (r.Level >= 5 && r.CurrentStat == "approvedByFM") || (r.Level >= 5 && r.CurrentStat == "approvedByCM")).ToList();
                        return View(res);
                    }
                    else
                    {
                        var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 8).ToList();
                        return View(res);
                    }
                }
                else
                {
                    var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 8).ToList();
                    return View(res);
                }
            }
            else if (role == ADMIN_ROLE)
            {
                var res = CRP_dbObj.viewNEW_CUS_HEADER.ToList();
                return View(res);
            }
            else
            {
                List<viewNEW_CUS_HEADER> emptyResult = new List<viewNEW_CUS_HEADER>();
                return View(emptyResult);
            }
        }

        public JsonResult SearchData(string SearchBy, string SearchValue)
        {
            Session["sorting"] = "All";
            ViewBag.sortString = Session["sorting"].ToString();

            try
            {
                role = Convert.ToInt16(Session["role"].ToString());
            }
            catch (Exception e)
            {
                Response.Redirect("/Login/UserLogin", false);
            }

            if (role == CO_ROLE)
            {
                if (SearchBy.Equals("Sales_Code"))
                {
                    var res = CRP_dbObj.viewNEW_CUS_HEADER.Where(r => r.Level >= 5 && r.SalesCode == SearchValue || SearchValue == null).ToList();
                    return Json(res, JsonRequestBehavior.AllowGet);
                }
                else if (SearchBy.Equals("Area"))
                {

FI.PORTAL/Views/CustomerRegistration/Index.cshtml
@model List<FI.PORTAL.dbconnect.viewNEW_CUS_HEADER>

@{ ViewBag.Title = "Index";
    String currentFind = ViewBag.findString; }

<link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<!-- JS For DataTables -->

<div class="row">
    <div class="col-md-12">
        <div class="card">

            <div class="card-header">
                <div class="row">
                    <form action="@Url.Action("", "CustomerRegistration")" method="get">
                        <div class="form-row align-items-center">
                            <div class="col-auto my-1">
                                <select class="custom-select mr-sm-2" name="findby">
                                    @if (currentFind == "All")
                                    {
                                        <option value="All" selected>All</option>
                                        <option value="Pending">Pending</option>
                                        <option value="Approved">Approved</option>
                                        <option value="Declined">Declined</option>
                                        }
                                     else if (currentFind == "Pending")
                                     {
                                        <option value="All">All</option>
                                        <option value="Pending" selected>Pending</option>
                                        <option value="Approved">Approved</option>
                                        <option value="Declined">Declined</option>
                                        }
                                     else if (currentFind == "Approved")
                                     {
                                        <option value="All">All</option>
                                        <option value="Pending">Pending</option>
                                        <option value="Approved" selected>Approved</option>
                                        <option value="Declined">Declined</option>
                                     }else if (currentFind == "Declined")
                                     {
                                        <option value="All">All</option>
                                        <option value="Pending">Pending</option>
                                        <option value="Approved">Approved</option>
                                        <option value="Declined" selected>Declined</option>
                                        }
                                     else
                                     {
                                         <option value="All" selected>All</option>
                                         <option value="Pending">Pending</option>
                                         <option value="Approved">Approved</option>
                                         <option value="Declined">Declined</option>
                                        }

                                </select>
                            </div>
                            <div class="col-auto my-1">
                                <button type="submit" class="btn btn-primary">Find</button>
                            </div>
                        </div>
                    </form>
                    <div style="margin-left: 2%">
                        <div class="form-row align-items-center">
                            <div class="col-auto my-1">
                                <label for="search_by">Search By: </label>
                            </div>
                            <div class="col-auto my-1">
                                <select id="search_by" class="custom-select mr-sm-2">
                                    <option value="Sales_Code">Sales Code</option>
                                    <option value="Area">Area</option>
                                    <option value="Rep_Name">REP Name</option>
                                </select>
                            </div>
                            <div class="col-auto my-1">
                                <input type="text" class="form-control" id="search_value" />
                            </div>
                            <div class="col-auto my-1">
                                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "CustomerRegistration")'">Reset</button>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex align-items-center" style="margin-left: 2%;">
                        <div style="display:none" id="loading_spinner">
                            <strong>Loading...</strong>
                            <div class="spinner-grow spinner-grow-sm ml-auto"></div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4>Customer Registration Requests</h4>
            </div>
            <div class="card-body">

                <div id="secposts" class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered small" style="width:100%" id="myTable">
                            <thead>
                                <tr>
                                    <th>Request ID</th>
                                    <th>Current Status</th>
                                    <th>Customer Name</th>
                                    <th>Sales Area Code</th>
                                    <th>Sales Area Name</th>
                                    <th>Created By</th>
                                    <th>Created Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody id="customer_reg">
                                @if (Model.Count == 0)
                                {
                    <tr>
                        <td colspan="8">No Records Found!</td>
                    </tr>
 }
                else
                {
                    foreach (var item in Model)
                    {
    <tr>
        <td>@item.CusReqID</td>
        <td>@item.CurrentStat</td>
        <td>@item.CusName</td>
        <td>@item.SalesCode</td>
        <td>@item.SalesAreaName</td>
        <td>@item.REPName</td>
        <td>@item.CreatedDate</td>

        <td>
            <a href="@Url.Action("CustomerRequestFormView", new { item.CusReqID})" class="btn btn-success btn-sm">View</a>
        </td>
    </tr>
}
}

                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>


<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script>
    $(document).ready(function () {
        $("#search_value").on('input', function () {
            $("#loading_spinner").show();
            var SearchBy = $("#search_by").val();
            var SearchVal = $("#search_value").val();
            var SetData = $("#customer_reg");
            SetData.html("");
            $.ajax({
                type: "post",
                url: "/CustomerRegistration/SearchData?SearchBy=" + SearchBy + "&SearchValue=" + SearchVal,
                contentType: "html",
                async: false,
                success: function (result) {
                    if (result.isRedirect) {
                        window.location.href = json.redirectUrl;
                    } else {
                        if (result.length == 0) {
                            SetData.append('<tr><td colspan="8">No data found!</td></tr>')
                        } else {
                            $.each(result, function (index, value) {
                                var date = new Date(parseInt(value.CreatedDate.substr(6)));
                                var customer_req_view = "<a href='CustomerRequestFormView?CusReqID=" + value.CusReqID + "' class='btn btn-success btn-sm'>View</a>"
                                console.log(value);
                                var Data = "<tr>" +
                                    "<td>" + value.CusReqID + "</td>" +
                                    "<td>" + value.CurrentStat + "</td>" +
                                    "<td>" + value.CusName + "</td>" +
                                    "<td>" + value.SalesCode + "</td>" +
                                    "<td>" + value.SalesAreaName + "</td>" +
                                    "<td>" + value.REPName + "</td>" +
                                    "<td>" + date.toLocaleString() + "</td>" +
                                    "<td>" + customer_req_view + "</td>" +
                                    "</tr>"

                                SetData.append(Data)
                            })
                        }
                    }
                },
                complete: function () {
                    $("#loading_spinner").hide();
                }
            })
        })
    })

</script>

<script>

    $(document).ready(function () {
        var SearchVal = $("#search_value").val();
        if (SearchVal != "") {
        $("#loading_spinner").show();
        var SearchBy = $("#search_by").val();
        var SetData = $("#customer_reg");
        SetData.html("");
        $.ajax({
            type: "post",
            url: "/CustomerRegistration/SearchData?SearchBy=" + SearchBy + "&SearchValue=" + SearchVal,
            contentType: "html",
            async: false,
            success: function (result) {
                if (result.isRedirect) {
                    window.location.href = json.redirectUrl;
                } else {
                    if (result.length == 0) {
                        SetData.append('<tr><td colspan="8">No data found!</td></tr>')
                    } else {
                        $.each(result, function (index, value) {
                            var date = new Date(parseInt(value.CreatedDate.substr(6)));
                            var customer_req_view = "<a href='CustomerRequestFormView?CusReqID=" + value.CusReqID + "' class='btn btn-success btn-sm'>View</a>"
                            console.log(value);
                            var Data = "<tr>" +
                                "<td>" + value.CusReqID + "</td>" +
                                "<td>" + value.CurrentStat + "</td>" +
                                "<td>" + value.CusName + "</td>" +
                                "<td>" + value.SalesCode + "</td>" +
                                "<td>" + value.SalesAreaName + "</td>" +
                                "<td>" + value.REPName + "</td>" +
                                "<td>" + date.toLocaleString() + "</td>" +
                                "<td>" + customer_req_view + "</td>" +
                                "</tr>"

                            SetData.append(Data)
                        })
                    }
                }
            },
            complete: function () {
                $("#loading_spinner").hide();
            }
        })
    }
    });
</script>